dist: xenial
sudo: false
language: ruby
notifications:
  email: false
rvm:
  - 2.4.1
jdk:
  - oraclejdk8
cache: bundler

before_script:
  - find data/ead -name '*.xml' | xargs xmllint --noout --schema data/xsd/ead.xsd
addons:
  apt:
    packages:
    - libxml2-utils
